nev=input("Kérem adja meg a vezetéknevét:")
nev1=input("Kérem adja meg a keresznevét:")
szuletesiev=int(input("Kérem adja meg a szültési évét:"))
print(29*"*")
print("Az ön  neve:", nev, nev1,)
print("Az életkora:", 2022-szuletesiev)